name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        port: [4567, 5678, 6789]
    steps:
      - uses: zhulik/setup-kinesis@v1.0.0
        with:
          port: ${{ matrix.port }}
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: gem install aws-sdk-kinesis
      - name: Test
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        run: ./test.rb ${{ matrix.port }}
